name: Generate Podcast Feeds
on: [push]
jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: samiksha-github123/podcast_generator@main
